export enum SERVER_ERRORS_ENUM {
    AUTH_ERROR = "AUTH_ERROR",
    TOKEN_NOT_AUTHORIZED = "TOKEN_NOT_AUTHORIZED",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    AMOUNT_NOT_AVAILABLE = "AMOUNT_NOT_AVAILABLE",
    ITEM_NOT_EXISTING = "ITEM_NOT_EXISTING",
    EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
    PAYMENT_METHOD_NOT_VALID = "PAYMENT_METHOD_NOT_VALID",
    PAYMENT_REQUIRES_ACTIONS = "PAYMENT_REQUIRES_ACTIONS"
}